### ISSUE TITLE
Off-by-one issue

### ISSUE THREAD

**Issue by daagar** [demonnic/TextGauges#1]
It appears that a bar filled at 100% will end up one character shorter than a bar that is less than 100%. 

Code used (hardcoding the percents):
```
  ui.bars.info:cecho("HP  ["..mip.hpcur.."/"..mip.hpmax.."]: ("..ui.hpbar:setValue(80)..")\n")
  ui.bars.info:cecho("HP  ["..mip.hpcur.."/"..mip.hpmax.."]: ("..ui.hpbar:setValue(100)..") ")
```
![image](https://user-images.githubusercontent.com/693706/72675205-6c75c280-3a46-11ea-9ccc-5233f776d5ef.png)

**Comment by demonnic** [comment]
I'll check into this a little later, definitely should not be doing that.

**Comment by demonnic** [comment]
Thanks for finding this. Fixed in https://github.com/demonnic/TextGauges/releases/tag/1.1
