### ISSUE TITLE
Overmax support

### ISSUE THREAD

**Issue by daagar** [demonnic/TextGauges#2]
Suggestion: When over 100%, it would be handy to have a representation of that in the text bars.

Assuming standard gauge characters (":" and "-"), my thought is to have the ':' characters colored a different color than normal to represent the percent over maximum.

**Comment by demonnic** [comment]
I could see perhaps having the gauge fold back over itself to represent overage, start changing color from the right backwards

**Comment by daagar** [comment]
I was thinking from the left instead of right, but that was indeed the general idea that I was having a heck of a time putting into words.

**Comment by demonnic** [comment]
Hmmm. I'll think about how best to implement this. May give both options. I kind of like it wrapping back over itself from the right, but I could see starting the bar over from the left.

**Comment by demonnic** [comment]
implemented in MDK 1.1.3 and TextGauge 1.2
